### PR TITLE
fix: message from peer chats were not found in place #2491

### LINKED ISSUE #2491: Search for messages in place does not consider peer chats

### PR DESCRIPTION
**Pull request by frolyo**

### CODE REVIEW

File: src/dotnet/Core/Constants.DebugMode.cs [hunk 1]
```diff
@@ -58,7 +58,7 @@ public static bool AudioPlaybackPlayMyOwnAudio
         public static readonly bool TranscriberGoogle = false;
 
         // Search
-        public static readonly bool OpenSearchRequest = false;
+        public static readonly bool OpenSearchRequest = true;
```
Comment (crui3er) [inline src/dotnet/Core/Constants.DebugMode.cs]: Do you enable debug mode for OpenSearch on purpose?

**Review by crui3er — APPROVED** [review]

File: src/dotnet/Core/Constants.DebugMode.cs (hunk 1 above)
Comment (frolyo) [reply src/dotnet/Core/Constants.DebugMode.cs]: fixed, thanks
